import { log } from "console";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import ItemNoteOfListShowNotes from "~/components/blimblom";
import Button from "~/components/button";

import { api } from "~/utils/api";

export default function Home() {
  
  const [haveData, setHaveData] = useState<String[]>([])

  const router = useRouter()
  
  const {data: notesData, isLoading} = api.create.listNotes.useQuery()

  useEffect(() => {
    // Verifica se estamos no ambiente do navegador antes de usar localStorage
    if (typeof window !== 'undefined') {
      console.log('oi');
      
      const arrayNotesLocalStorage: String[] = []

      notesData?.forEach(note => {
        // let noteJson = {id: note.id, title: note.title, content: note.content}
        let titleLocalStorage = note.title
        localStorage.setItem(titleLocalStorage, JSON.stringify(note));

        let dataLocalStorage = localStorage.getItem(titleLocalStorage);
        if (dataLocalStorage) {
          arrayNotesLocalStorage.push(dataLocalStorage);
        }
      });

      setHaveData(arrayNotesLocalStorage); // Atualiza o estado haveData
    }
  }, [notesData]); 

  useEffect(() => {
    // Aqui, haveData será atualizado com os dados de localStorage
    if (haveData) {
      console.log('Há dados no localStorage:', haveData);
    } else {
      console.log('Não há dados no localStorage');
    }
  }, [haveData]); // Executa sempre que haveData for alterado

  const handleNavegacao = () => {
    router.push('/createNote');
  };

  if (isLoading) return <p>loading...</p>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen">
        
          {
            
            !haveData ? (
              <>
                <div id="all_Content" className="flex flex-col justify-center items-center h-full w-full bg-blue-500">
                  <div>
                    <h1 className="bg-green-500">You don't have any note</h1>
                    <Button onClick={handleNavegacao}/>
                  </div>
                </div>
              </>
            ) : (
            <>
              <div id="all_Content" className="flex flex-col justify-start items-center h-full w-full bg-blue-500">

                <h1 className="bg-red-500 mt-8">Personal Notes</h1>

                <div id="space_Notes" className="flex mt-3 bg-gray-500 mx-8">
      
                  <div id="side_Menu" className="w-3/3 bg-white flex flex-col justify-center items-end">
                    <ul>
                      {notesData?.map((note) => (
                        <ItemNoteOfListShowNotes key={note.id} title={note.title} content={note.content}/>
                      ))}
                    </ul>
                    <Button onClick={handleNavegacao}/>
                  </div>
                </div>
              </div>
            
            </>)
          }
      </main>
    </>
  );
}
