import { Note } from "@prisma/client";
import { log } from "console";
import { Url } from "next/dist/shared/lib/router/router";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import ItemNoteOfListShowNotes from "~/components/blimblom";
import Button from "~/components/button";

import { api } from "~/utils/api";

export default function Home() {

  const router = useRouter()

  const [allNotesByDb, setAllNotesByDb] = useState<Note[]>([])
  const { data: notesData, isLoading, isSuccess} = api.personalNote.listNotes.useQuery()
  
  console.log("Antes da requisição dar sucesso");
  
  useEffect(()=>{ 
    console.log("dentro do effect antes de dar sucesso")
    if (isSuccess) {
      console.log("deu sucesso");
      
      setAllNotesByDb(notesData)
    }

  }, [notesData])

  const handleNavegacao = () => {
    router.push('/createNote');
  };
  return (
    <>
      <Head>
        <title>Personal Notes</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen w-screen">
        
          {
            
            allNotesByDb.length == 0 ? (
              <>
                <div id="all_Content" className="flex flex-col justify-center items-center h-full w-full bg-blue-500">
                  <div>
                    <h1 className="bg-green-500">You don't have any note</h1>
                    <Button onClick={handleNavegacao} value="Write a new note" className="bg-gray-500 border-2 w-48 mt-2"/>
                  </div>
                </div>
              </>
            ) : (
            <>
              <div id="container" className="flex justify-center items-start h-full w-full bg-[#E5E1DA]">
                <div id="all_Content" className="flex flex-col justify-between mt-8 max-w-80 w-80 max-h-[678px]">
                  <h1 className="mb-3 text-center text-2xl">Personal Notes</h1>

                  <div id="side_Menu" className="w-full flex flex-col justify-center items-center max-h-[638px] h-full">
                    <div className="w-full flex justify-center items-start h-full">
                      <ul className="w-full h-full  p-1 rounded-md bg-[#FBF9F1] max-h-[578px] overflow-scroll">
                        {allNotesByDb.map((note) => (
                          <ItemNoteOfListShowNotes id={note.id} title={note.title} content={note.content}/>
                        ))}
                      </ul>
                    </div>
                    <Button onClick={handleNavegacao} value="Write a new note" className="bg-[#92C7CF] w-full mt-2 p-3 rounded-md"/>                
                  </div>
                </div>
              </div>           
            </>)

          }
      </main>
    </>
  );
}
